### ISSUE TITLE
[Feature Request]: USB HID Not working 

### ISSUE THREAD

**Issue by Acidragon** [EmulationCollective/XBSX2#10]
### Description

In games where text chat are mandatory to have a good communication while playing (like SOCOM 2), the USB keyboard I plug to my Xbox does not seem to work, unlike on Aether where it worked perfectly, would be nice to enable the use of it on XBSX2 aswell.

### Reason

As explained above most games need text chat to improve quality of online play. 

### Examples

I don’t have any examples to show per se, as it’s pretty self explanatory. It used to work on the older Xbox emulators.

**Comment by SternXD** [comment]
Hello, I apologize for the delay in responding. I’m planning to release version 2.0.8.1 later today. Once it’s available, could you please try it on that build?

**Comment by Acidragon** [comment]
> Hello, I apologize for the delay in responding. I’m planning to release version 2.0.8.1 later today. Once it’s available, could you please try it on that build?

Ok can you let me know when its released so I may test. Thank you!

**Comment by SternXD** [comment]
> > Hello, I apologize for the delay in responding. I’m planning to release version 2.0.8.1 later today. Once it’s available, could you please try it on that build?
> 
> Ok can you let me know when its released so I may test. Thank you!

I just released it :)

**Comment by Acidragon** [comment]
> > > Hello, I apologize for the delay in responding. I’m planning to release version 2.0.8.1 later today. Once it’s available, could you please try it on that build?
> > 
> > 
> > Ok can you let me know when its released so I may test. Thank you!
> 
> I just released it :)

The HID Keyboard still does not work at all, not even in games like socom for text chat but at the time of making any custom input profile for a game, when you have to enter the name of the input, you can't use the dashboard keyboard or a physical one to enter a name for it.

**Comment by SternXD** [comment]
You have to press `Y` for the keyboard to show up.

**Comment by Acidragon** [comment]
> You have to press `Y` for the keyboard to show up.

You were right, pressing Y it works in order to create input profiles names, however, I still can't use the physical keyboard playing games with keyboard support for text chat, like the SOCOM games, due to the HID Keyboard function not being enabled in the code, this issue has been happening since the first build of XBSX2 by the way. It works on AetherSX2 UWP though.

Thank you!

**Comment by SternXD** [comment]
Hmm. Sadly AetherSX2 is/was closed source I can look at enabling it but no promises.

**Comment by SternXD** [comment]
Was not able to get this working may look at it more later on but until then not planned.
